parameters:
    overblog_stomp.publisher.class: Overblog\StompBundle\Stomp\Publisher
    overblog_stomp.consumer.class: Overblog\StompBundle\Stomp\Consumer
    overblog_stomp.connection.class: Overblog\StompBundle\Stomp\Connection