parameters:
    overblog_active_mq.publisher.class: Overblog\ActiveMqBundle\ActiveMq\Publisher
    overblog_active_mq.consumer.class: Overblog\ActiveMqBundle\ActiveMq\Consumer
    overblog_active_mq.connection.class: Overblog\ActiveMqBundle\ActiveMq\Connection